#!/bin/bash
# Shuttle environment variables
# Generated by 00_set_env.sh on Wed Jun  4 21:04:17 AEST 2025

export SHUTTLE_CONFIG_PATH="/home/mathew/shuttle/config.conf"
export SHUTTLE_VENV_PATH="/home/mathew/shuttle/.venv"
export SHUTTLE_WORK_DIR="/home/mathew/shuttle/work"

# Display current settings
echo "Shuttle environment loaded:"
echo "  SHUTTLE_CONFIG_PATH=$SHUTTLE_CONFIG_PATH"
echo "  SHUTTLE_VENV_PATH=$SHUTTLE_VENV_PATH"
echo "  SHUTTLE_WORK_DIR=$SHUTTLE_WORK_DIR"
