[paths]
source_path = /mnt/in
destination_path = /mnt/out
quarantine_path = /mnt/quarantine
log_path = /var/log/shuttle
hazard_archive_path = /mnt/hazard
hazard_encryption_key_path = /etc/shuttle/shuttle_public.gpg
ledger_file_path = /etc/shuttle/ledger/ledger.yaml

[settings]
max_scan_threads = 1
delete_source_files_after_copying = True
defender_handles_suspect_files = True
on_demand_defender = True
on_demand_clam_av = False
throttle = True
throttle_free_space_mb = 100
throttle_max_file_count_per_run = 1000
throttle_max_file_volume_per_run_mb = 1024

[logging]
log_level = INFO

[scanning]
malware_scan_timeout_seconds = 60
malware_scan_timeout_ms_per_byte = 0.01
malware_scan_retry_wait_seconds = 30
malware_scan_retry_count = 3

[notification]
notify = False
notify_summary = False
recipient_email = admin@example.com
recipient_email_error = admin@example.com
recipient_email_summary = admin@example.com
recipient_email_hazard = admin@example.com
sender_email = shuttle@yourdomain.com
smtp_server = smtp.yourdomain.com
smtp_port = 587
username = shuttle_notifications
password = your_secure_password_here
use_tls = True

