#!/bin/bash
# Shuttle environment variables
# Generated by 02_env_and_venv.sh on Tue Jun 10 21:29:01 AEST 2025

export SHUTTLE_CONFIG_PATH="/home/mathew/shuttle/config/config.conf"
export SHUTTLE_TEST_WORK_DIR="/home/mathew/shuttle/test_area"
export SHUTTLE_TEST_CONFIG_PATH="/home/mathew/shuttle/test_area/test_config.conf"

# Display current settings
echo "Shuttle environment loaded:"
echo "  SHUTTLE_CONFIG_PATH=$SHUTTLE_CONFIG_PATH"
echo "  SHUTTLE_TEST_WORK_DIR=$SHUTTLE_TEST_WORK_DIR"
echo "  SHUTTLE_TEST_CONFIG_PATH=$SHUTTLE_TEST_CONFIG_PATH"
